name: Grab Latest Class Data

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute script
      run: python main.py

    - name: Commit to repo
      run: |
        git config --local user.name 'jstnf/cron-commit-testing'
        git config --local user.email 'cron-commit-testing[bot]@justinf.dev'
        git add .
        # "echo" returns true so the build success, even if no changed files
        git commit -m 'Update generated files' || echo
        git push